name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test Job
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18
      - name: Install Packages
        run: npm ci
        working-directory: ./wordle-web
      - name: Generate
        run: npm run generate
        working-directory: ./wordle-web
      - name: Run Vitest
        run: npm run test
        working-directory: ./wordle-web
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    name: Deploy to Azure
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_FOREST_0EB1D671E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./wordle-web/.output/public"
